name: Merge Status Check

on:
  pull_request:
    types: [ closed ]

jobs:
  merge_status_check:
    env:
      SHA: ${{ github.sha }}
      URL: ${{ github.event.repository.statuses_url }}
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo XXXXXXXXXXXXXXXXXXXXXXXX
        echo XX MERGE STATUS CHECK XX
        echo XXXXXXXXXXXXXXXXXXXXXXXX
        URL="${URL//\{sha\}/$SHA}"
        echo XXXX $URL
        curl "$URL"
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -d '{"state":"success"}' \
        ;
