name: Merge Status Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  merge_status_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo OK.
