name: Merge Status Check

on:
  pull_request:
    types: [ closed ]

jobs:
  merge_status_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo XXXXXXXXXXXXXXXXXXXXXXXX
        echo XX MERGE STATUS CHECK XX
        echo XXXXXXXXXXXXXXXXXXXXXXXX
